version: '3'

services:
  nginx:
    build:
      context: backend/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - transcendence
    ports:
      - "9001:9001"
      - "9002:9002"
    volumes:
      - ./frontend:/usr/share/nginx/html/
      - ./backend/nginx/conf.d:/etc/nginx/conf.d/
      - ${KEY_}:/etc/nginx/ssl/pong.key
      - ${CERT_}:/etc/nginx/ssl/pong.crt
    restart: always
    depends_on:
      - ruby
      - db
    env_file: .env
    
  
  ruby:
    build:
      context: backend/ruby
      dockerfile: Dockerfile
    container_name: ruby
    networks:
      - transcendence
    ports:
      - "8080:8080"
      - "4567:4567"
    volumes:
      - ./backend/ruby/srcs:/var/server
      - ${KEY_}:/var/ssl/pong.key
      - ${CERT_}:/var/ssl/pong.crt
    restart: always
    depends_on:
      - db
    env_file: .env
  
  db:
    build:
      context: backend/db
      dockerfile: Dockerfile
    container_name: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pong
    networks:
      - transcendence
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./local/db
      o: bind
    name: db_data_volume

networks:
  transcendence:
    driver: bridge