version: '3'

services:
  nginx:
    build:
      context: backend/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./pongGame:/var/www/public/html
      - ./backend/nginx/conf.d:/etc/nginx/conf.d/
    restart: always
  
  ruby:
    build:
      context: backend/ruby
      dockerfile: Dockerfile
    container_name: ruby
    ports:
      - "8080:8080"
    volumes:
      - ./backend/ruby/srcs:/var/server
    restart: always