version: '3'

services:
  nginx:
    build:
      context: backend/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./pongGame:/var/www/public/html
      - ./backend/nginx/conf.d:/etc/nginx/conf.d/
      - ./backend/nginx/tools:/etc/nginx/ssl/
    restart: always
    depends_on:
      - ruby
      - db
  
  ruby:
    build:
      context: backend/ruby
      dockerfile: Dockerfile
    container_name: ruby
    ports:
      - "8080:8080"
    volumes:
      - ./backend/ruby/srcs:/var/server
      - ./backend/nginx/tools:/var/ssl/
    restart: always
    depends_on:
      - db
  
  db:
    build:
      context: backend/db
      dockerfile: Dockerfile
    container_name: db
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pong
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
  
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./local/db
      o: bind
    name: db_data_volume
